name: Slack Notification

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Slack notification
        uses: rtCamp/action-slack-notify@v2
